### PR TITLE
[CN] Add CI for CN runtime testing capability 

### PR DESCRIPTION
**Pull request by septract**
Runs the CN runtime testing capability over specially-modified examples from the CN tutorial. 

Note: 
* The CI script checks out branch #439, which includes necessary test script modifications. Before merging this branch, we need to merge #439 and then the checkout target should be changed to `cerberus:master`
* The CI script applies the runtime testing to `cn-tutorial:cn-runtime-testing`. This branch adds `main()` functions to the tutorial examples, and so it cannot be merged into `cn-tutorial:main`. It's okay to merge without resolving this, but we should fix it sooner rather than later.

### CODE REVIEW

**Comment by septract** [comment]
@rbanerjee20

**Comment by rbanerjee20** [comment]
I've approved #439 now so once that is merged I'm happy to approve and merge this PR too.

**Comment by septract** [comment]
@rbanerjee20 Looks like this is working! If you're happy with the PR, go ahead and merge.

**Comment by septract** [comment]
Note this PR still points to a branch on `cn-tutorial` - see here: https://github.com/rems-project/cn-tutorial/issues/70

Okay to merge as is, but we should fix this at some point soon. 

@dc-mak

**Comment by dc-mak** [comment]
Just for posterity, https://github.com/rems-project/cerberus/commit/8722102c458b0ca03b01f9de66c23ba8ef865180 has the wrong issue number, it should be #489 but I got it wrong in a rush.

**Pull request merged**
