### PR TITLE
Add benchmarking CI that generates graphs on updates to master

### PR DESCRIPTION
**Pull request by jprider63**
Reopens #530.

### CODE REVIEW

**Comment by dc-mak** [comment]
Thanks. Where can I find a successful run of the new CI of this PR at this commit?

**Comment by jprider63** [comment]
It passed [here](https://github.com/GaloisInc/cerberus/actions/runs/10585515969/job/29332260659) but with a different commit since it didn't include the revert. I'll rerun it to make sure.

**Comment by jprider63** [comment]
It just [passed here](https://github.com/GaloisInc/cerberus/actions/runs/10601778835/job/29382330261).

**Comment by jprider63** [comment]
It looks like this succeeded and the benchmark data is being pushed [here](https://github.com/rems-project/cerberus/tree/gh-pages/dev/bench)! To view the graphs, you'll need to [enable the pages setting](https://docs.github.com/en/pages/quickstart) for the `gh-pages` branch.

**Comment by dc-mak** [comment]
@kmemarian says that `/dev/bench` is not an option for us, only `/ (root)` or `/docs`

Link: https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#about-publishing-sources

> You can specify which branch and folder to use as your publishing source. The source branch can be any branch in your repository, and the source folder can either be the root of the repository (/) on the source branch or a /docs folder on the source branch. Whenever changes are pushed to the source branch, the changes in the source folder will be published to your GitHub Pages site.

**Comment by jprider63** [comment]
The graphs are being displayed [here](https://rems-project.github.io/cerberus/dev/bench/). Do you want them to live at a different path?

**Comment by dc-mak** [comment]
No no, just confusion on my part. Very cool, thank you!

**Pull request merged**
