### PR TITLE
[CN] Add parsing of a->b expressions

### PR DESCRIPTION
**Pull request by septract**
Work on addressing #328

Progress: 
- [x] Got CN to parse expressions by reusing the code from `CExpr_memberof` 
- [ ] Implement the semantics by desugaring

### CODE REVIEW

**Comment by septract** [comment]
I could use some input about how to complete this feature. My guess is this should work as follows: 
1. Add a constructor to the `cn_expr_` type, `CNExpr_arrow` (in `frontend/model/cn.lem`)
2. Parse expressions of the form a->b to `CNExpr_arrow` (in `parsec/c/c_parser.mly`)
3. Modify `desugar_cn_expr` to convert `CNExpr_arrow` to `CNExpr_memberof`, and inject a synthetic `CNExpr_deref` somewhere to complete the translation (in `frontend/model/cabs_to_ail.lem`). 

Alternative approach: I could also imagine changing the interpretation of `CNExpr_arrow` by modifying `translate_cn_expr` in `backend/cn/compile`. 

Is this on the right track @cp526 / @dc-mak ? 

(Note, we also have to do something similar for some a `CNExpr_arrowupdate` constructor)

**Comment by dc-mak** [comment]
I think you might not even need to add the constructor - perhaps to get something working and test it, you can just have the parser `a->b` produce a `(member(deref(a), b)` in the Cabs and the rest of the pipeline should take care of it. Or you can do it at something like in `desugar_cn_expr`
```
arrow (a,b) ->
    desugar (member(deref(a), b))
```
Or in backend/cn/compile. 

I'm confused about an `arrowupdate` constructor though. If not too much of a tangent, can you explain?

**Comment by septract** [comment]
I assumed that it would be needed as the equivalent of the `CNExpr_memberupdate` constructor, but perhaps I misunderstood what that constructor represents?

**Comment by dc-mak** [comment]
The below passes CN (with arrow soon to be valid, but commented out for now). I can't see understand if arrow update makes sense as a concept.
```c
struct point {
    int x;
    int y;
};

void f() {
    struct point origin = { .x = 0, .y = 0 };
    /*@ assert (origin.x == 0i32); @*/ // -- member
    struct point not_origin = origin;
    not_origin.y = 1;
    /*@ assert (not_origin == { y: 1i32, ..origin});@*/ // member update
    struct point *p = &origin;
    // /*@ assert (p->x == 0i32); @*/ // -- arrow (when implemented)
    /*@ assert ((*p).x == 0i32); @*/ // -- arrow (as currently)
    struct point *q = &not_origin;
    /*@ assert (*q == { y: 1i32, ..*p});@*/ // how would arrow update be different/better?
}
```

**Comment by septract** [comment]
Thanks, I think I just misunderstood the update construct! I'll get this PR fixed and submitted for review.

**Comment by septract** [comment]
Closing in favor of #396

**Pull request closed without merging**
