### PR TITLE
Fix z3 install and CN tests for Dockerfiles

### PR DESCRIPTION
**Pull request by podhrmic**
The nighly docker build hid an error in docker invocation. I fixed the invocation of `run-cn.sh` and properly installed z3 via opam in both docker images.

### CODE REVIEW

**Comment by podhrmic** [comment]
@dc-mak this fixes the error in https://github.com/rems-project/cerberus/actions/runs/11784243588/job/32823035384

**Comment by dc-mak** [comment]
Hmm, to minimise this in the future, can you please also adjust the docker.yml to run on any PR that edits the docker.yml or any Dockerfiles? https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request

**Comment by podhrmic** [comment]
@dc-mak I tried - but as you can see, the on-change triggers do not seem to work very well (or at all). This matches my previous experience, so if you have an idea how to fix this go ahead, otherwise I would just merge as is, as moving forward we shouldn't need to change the Dockerfiles much

**Comment by dc-mak** [comment]
It seems to have triggered the workflow but I did it when the actual scheduled job is also running, so it is waiting behind that to finish... https://github.com/rems-project/cerberus/actions/runs/11803628827

**Comment by podhrmic** [comment]
@dc-mak I would also recommend that the `test-docker-images` job depends on the build job, such that you test the newly built images. 

Adding:
```
needs:
  needs: [docker-release-redhat, docker-release-ubuntu]
```

Indeed, this will only work on `master` branch, as you are limiting which branch can push the new images, but probably good enough for now

**Comment by dc-mak** [comment]
> @dc-mak I would also recommend that the `test-docker-images` job depends on the build job, such that you test the newly built images.
> 
> Adding:
> 
> ```
> needs:
>   needs: [docker-release-redhat, docker-release-ubuntu]
> ```
> 
> Indeed, this will only work on `master` branch, as you are limiting which branch can push the new images, but probably good enough for now

Fair point, feel free to add and push

**Comment by dc-mak** [comment]
https://docs.docker.com/build/ci/github-actions/share-image-jobs

https://docs.docker.com/reference/cli/docker/buildx/build/#output

There also seem to be some caching options of some sort.

**Comment by podhrmic** [comment]
@dc-mak I updated the job dependency. I cannot use the caching, because I am building the images with attestation, and that is allowed only if you directly push the images into the registry (`attests: type=sbom` and `provenance: mode=max`). I think this is good enough for now, thanks for tweaking the push conditions!

**Comment by podhrmic** [comment]
@dc-mak any reason not to merge this?

**Comment by dc-mak** [comment]
I’ve been writing 2000 words/day.

**Pull request merged**
